---
- name: Install default-jdk
  hosts: all
  become: yes

  tasks:
    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest
        force_apt_get: yes

    - name: Install app
      apt:
        name: default-jdk
        state: present

- name: Application building
  hosts: build
  become: yes

  tasks:
    - name: Install git & maven
      apt:
        pkg:
          - git
          - maven

    - name: Directory preparation
      file:
        path: /home/git
        state: directory
        mode: '0777'
      become: yes

    - name: Ensure app was downloaded
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /home/git
        clone: yes
        update: yes
        force: yes

    - name: Ensure app was building
      command: mvn package
      become: yes
      args:
        chdir: /home/git/

- name: Run application
  hosts: tomcat
  become: yes

  tasks:
    - name: Install Tomcat 9
      apt:
        name: tomcat9
        state: present

    - name: Ensure Tomcat 9 service is started
      service:
        name: tomcat9
        state: started

    - name: Copy app from remote host
      synchronize:
        src: /home/git/target/hello-1.0.war #путь на машине с которой копируем
        dest: /var/lib/tomcat9/webapps #путь на машине на которую копируем
      delegate_to: 34.88.177.55 #машина на которую копируем

    - name: Application deploing
      service:
        name: tomcat9
        state: restarted
